apiVersion: v1
kind: ConfigMap
metadata:
  name: flagd-config
data:
  flags.json: |
    {
      "$schema": "https://flagd.dev/schema/v0/flags.json",
        "flags": {
          "ops-fulfillment-mode": {
            "state": "ENABLED",
            "variants": {
              "standard": "standard",
              "express": "express"
            },
            "defaultVariant": "standard",
            "targeting": {
              "if": [
                { "==": [{ "var": "tenant" }, "premium"] },
                "express",
                null
              ]
            }
          },
          "new-pricing-algo": {
            "state": "ENABLED",
            "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "off",
          "targeting": {
            "if": [
              { "==": [{ "var": "tenant" }, "premium"] },
              "on",
              null
            ]
          }
        },
        "order-tier": {
          "state": "ENABLED",
          "variants": {
            "standard": "standard",
            "premium": "premium"
          },
          "defaultVariant": "standard",
          "targeting": {
            "if": [
              { "starts_with": [{ "var": "targetingKey" }, "u-vip-"] },
              "premium",
              null
            ]
          }
        },
        "ui-homepage-banner": {
          "state": "ENABLED",
          "variants": {
            "control": "control",
            "spring-sale": "spring-sale"
          },
          "defaultVariant": "control",
          "targeting": {
            "if": [
              { "starts_with": [{ "var": "targetingKey" }, "u-vip-"] },
              "spring-sale",
              null
            ]
          }
        },
        "ui-member-perks": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "off",
          "targeting": {
            "if": [
              { "starts_with": [{ "var": "targetingKey" }, "u-vip-"] },
              "on",
              null
            ]
          }
        }
      }
    }
