apiVersion: v1
kind: Service
metadata:
  name: flagd
spec:
  selector:
    app: flagd
  ports:
    - name: grpc
      port: 8013
      targetPort: 8013
    - name: management
      port: 8014
      targetPort: 8014
    - name: ofrep
      port: 8016
      targetPort: 8016
